In test calls .csv there exists neighborhoods with negative Ids which are breaking the system

In [82]:
import numpy as np

In [83]:
test_calls = np.genfromtxt("../test/austin-data/austin_test_calls.csv", delimiter=",")
test_calls_s = np.genfromtxt("../test/austin-data/austin_test_calls.csv", delimiter=",",dtype = str)

In [84]:
test_calls.shape

(30197, 59)

In [94]:
bad_index = np.where(test_calls[:,1] > 209)
bad_index[0].shape
bad_index


(array([6421, 6422], dtype=int64),)

In [107]:
#remove negative indixes
bad_index = np.where(test_calls[:,1] < 0)
good_index = []
good_index = np.append(good_index, [0], axis=None) #add header
no_neg = np.where(test_calls[:,1] > 0)
no_great = np.where(test_calls[:,1] < 209)
intersect = np.intersect1d(no_neg, no_great)
good_index =  np.append(good_index, intersect, axis=None)
good_index = good_index.astype(int)
good_index[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
print(no_neg[0].shape)
print(no_great[0].shape)
print(intersect.shape)
intersect

(30148,)
(30194,)
(30146,)


array([    1,     2,     3, ..., 30194, 30195, 30196], dtype=int64)

In [77]:
#remove indixes greater than number of neighborhoods
test_calls[bad_index,1]

array([[  -10., -8528., -8528., -8528., -8528., -8528., -8528., -8528.,
        -8528., -8528., -8528., -8528., -8528., -8528., -8528., -8528.,
        -8528., -8528., -8528., -8528.,   -10., -8528., -8528., -8528.,
        -8528., -8528., -8528., -8528., -8528., -8528., -8528., -8528.,
        -8528., -8528., -8528., -8528., -8528., -8528., -8528., -8528.,
        -8528., -8528., -8528., -8528., -8528., -8528., -8528., -8528.]])

In [109]:
test_calls_good = test_calls_s[good_index,:] #remove who row

In [111]:
test_calls_good = test_calls_good.reshape(30147,59) #GOTTA CHANGE THIS EVERY TIME THE SHAPE CHANGES. todo
print(test_calls_good.shape)
print(test_calls.shape)

(30147, 59)
(30197, 59)


In [112]:
np.savetxt('../test/austin-data/austin_test_calls_update1.csv', test_calls_good, delimiter=',', fmt='%s')